---
title: "결정트리의 결정경계 시각화"
author: "202116927 오준석"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


iris 데이터에서 꽃의 품종을 분류하는 결정트리 모델 만들고 트리를 시각화하기

```{r}
# 라이브러리 불러오기
library(rpart)
library(rpart.plot)
library(ggplot2)

# iris 데이터셋 불러오기
data(iris)

# 결정트리 모델 학습
model <- rpart(Species ~ ., data = iris)

# 결정트리 시각화
rpart.plot(model)

```

결정 경계를 시각화해보기


```{r}
# 라이브러리 불러오기
library(ggplot2)
library(gridExtra)

# iris 데이터셋에서 두 개의 특징만 선택
iris_selected <- iris[, c("Sepal.Length", "Sepal.Width", "Species")]

# 결정트리 모델 학습 (선택한 두 특징만 사용)
model_selected <- rpart(Species ~ Sepal.Length + Sepal.Width, data = iris_selected)
#iris_selected를 사용하므로 Species~.을 사용해도 됨

# 시각화를 위한 그리드 데이터 생성
x_min <- min(iris_selected$Sepal.Length) - 1
x_max <- max(iris_selected$Sepal.Length) + 1
y_min <- min(iris_selected$Sepal.Width) - 1
y_max <- max(iris_selected$Sepal.Width) + 1

grid <- expand.grid(
  Sepal.Length = seq(x_min, x_max, by = 0.01),
  Sepal.Width = seq(y_min, y_max, by = 0.01)
)

# 그리드 데이터에 대한 예측
grid$Species <- predict(model_selected, grid, type = "class")

# 원래 데이터와 결합
plot_data <- rbind(
  transform(iris_selected, Set = "Training Data"),
  transform(grid, Set = "Decision Boundary")
)

# ggplot으로 시각화
p <- ggplot(plot_data, aes(x = Sepal.Length, y = Sepal.Width, color = Species, fill = Species)) +
  geom_point(alpha = 0.3) +
  facet_wrap(~Set) +
  theme_minimal() +
  labs(title = "Decision Tree Decision Boundary",
       x = "Sepal Length",
       y = "Sepal Width")

# 그래프 출력
print(p)

```
